# Standards: 0.1
---
- name: Kill skype
  command: killall Skype
  register: skype_kill
  failed_when: skype_kill.rc != 0 and "No matching processes belonging to you were found" not in skype_kill.stderr
  become: "{{ (skype_user != ansible_user_id) | bool }}"
  become_user: "{{ skype_user }}"

- name: Start skype
  when: skype_started
  command: open -j /Applications/Skype.app
  become: "{{ (skype_user != ansible_user_id) | bool }}"
  become_user: "{{ skype_user }}"

...
